modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="badsunrise"
version="1.0.0"
displayName="The Bad Sunrise"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="youar, MCreator"

[[dependencies.badsunrise]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



